server:
    port: 9981
    context-path: /ctb/
logging:
    level:
        tk.mybatis: DEBUG
spring:
    datasource:
        name: ctb
        #url: jdbc:oracle:thin:@127.0.0.1:1521/XE
        #username: system
        #password: m123
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: oracle.jdbc.OracleDriver

        url: jdbc:mysql://127.0.0.1:3306/CTB?serverTimezone=GMT
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select * from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
